version: '3'
services:
    php:
        build: .docker
        restart: always
        volumes:
#            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
#            - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - .:/var/www/html
        user: www-data
        env_file:
            - .env
            - .env.local
volumes:
    postgres-data-volume: #> docker volume create --name postgres-data-volume -d local
        external: true
